### ISSUE TITLE
Error with wasm-bindgen call

### ISSUE THREAD

**Issue by nuzzles** [jetli/trunk-action#26]
Hey, do you mind taking a look at https://github.com/simbleau/website/actions/runs/3863670049/jobs/6585992494 ?

For some reason, my CI is breaking now on the wasm-bindgen call. This wasn't always the case.

```yaml
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Trunk
        uses: jetli/trunk-action@v0.2.0
        with:
          version: "latest"

      - name: Build | Trunk
        run: trunk build --release
```
