### ISSUE TITLE
404 when using fixed version

### ISSUE THREAD

**Issue by MeoMix** [jetli/trunk-action#29]
Hi!

Trunk v0.18.0 was released today. I'm encountering a bug with it and wanted to revert back to the previous version.

I changed my config from:

```
      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'
```

to:

```
      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: '0.17.5'
```

but it 404s.

It's trying to pull from: `https://github.com/thedodd/trunk/releases/download/0.17.5/trunk-x86_64-unknown-linux-gnu.tar.gz `

but the correct URL is now: `https://github.com/trunk-rs/trunk/releases/download/v0.17.5/trunk-x86_64-unknown-linux-gnu.tar.gz`
